name: Run inside EIC shell on CVMFS

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build-and-run:
    # Note: this workflow must run on linux 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
      with:
        cvmfs_repositories: 'singularity.opensciencegrid.org'
    - uses: eic/run-cvmfs-osg-eic-shell@main
      with:
        release-platform: "jug_xl:nightly"
        run: |
          eic-info
