name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: eic/setup-cvmfs@main
    - uses: eic/setup-spack@main
    - name: Run CI scripts
      run: |
        source ${SPACK_ROOT}/share/spack/setup-env.sh
        if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
