name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a script
      run: if [ -f ./run-ci.sh ] ; ./run-ci.sh ; fi
