name: EIC CI against CVMFS Software Stack

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup CVMFS
      run: |
      # Install cvmfs
      wget -q https://ecsft.cern.ch/dist/cvmfs/cvmfs-release/cvmfs-release-latest_all.deb
      sudo dpkg -i cvmfs-release-latest_all.deb
      sudo apt-get -q update
      sudo apt-get -q -y install cvmfs cvmfs-config-default
      rm -f cvmfs-release-latest_all.deb
      # Setup eic.opensciencegrid.org
      sudo mkdir -p /etc/cvmfs
      echo "CVMFS_REPOSITORIES=eic.opensciencegrid.org" | sudo tee /etc/cvmfs/default.local
      echo "CVMFS_HTTP_PROXY=DIRECT" | sudo tee -a /etc/cvmfs/default.local
      sudo cvmfs_config setup
      # Configure autofs
      echo "+dir:/etc/auto.master.d" | sudo tee /etc/auto.master
      sudo mkdir -p /etc/auto.master.d
      echo "/cvmfs /etc/auto.cvmfs" | sudo tee /etc/auto.master.d/cvmfs.autofs
      sudo service autofs start  

    - name: Run CI scripts
      run: if [ -d ./ci.d ] ; then run-parts ./ci.d ; fi
